name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  e2e-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: SetUp Docker  
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: docker build -t playwright-tests -f ./dockerfile

    - name: Run E2E tests
      run: docker run --rm playwright-tests

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
          name: playwright-report
          path: playwright-report

